# Generated by Django 2.0.5 on 2020-12-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='svn_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svn_name', models.CharField(max_length=128, unique=True)),
                ('path', models.CharField(max_length=128, unique=True)),
                ('last_change_person', models.CharField(max_length=128)),
                ('last_change_date', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Yonghu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonghu_id', models.CharField(max_length=32, unique=True)),
                ('yonghu_secret', models.CharField(max_length=32)),
            ],
        ),
    ]
