# Generated by Django 2.0.5 on 2020-12-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='svn_assets',
            new_name='svn_asset',
        ),
    ]
