# Generated by Django 2.0.5 on 2020-12-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201231_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svn_asset',
            name='path',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='svn_asset',
            name='svn_name',
            field=models.CharField(max_length=128),
        ),
    ]
